#server
server.port=${WEB_SERVER_PORT:8080}
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
#----------------
bot.username=${BOT_USERNAME}
bot.token=${BOT_TOKEN}
bot.creatorId=${BOT_CREATOR_ID}
#db
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL:10}
spring.jpa.packages-to-scan=vlsurhai.ganokbot.persistence
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
#locale
spring.messages.basename=messages
spring.messages.encoding=UTF-8
#captcha
captcha.messages.cleanup.delay-ms=60000
captcha.expiration-time.minutes=60
captcha.max-attempts=5
captcha.height=75
captcha.width=180
captcha.length=5
#spam-handling
spam.max-messages=10
spam.time-window.seconds=10
spam.mute-duration.minutes=15
#complaints
complaints.required-to-mute=5
complaints.expiration-time.days=1
#aws