name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 220872168257
  ECR_REGISTRY: 220872168257.dkr.ecr.eu-central-1.amazonaws.com
  ECR_REPOSITORY: ohsureguy/ganokbot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} --target ganokbot-runtime .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ganokbot

            git pull origin master

            # Fetch secrets from SSM and create .env
            aws configure set region ${{ env.AWS_REGION }}
            echo "WEB_SERVER_PORT=$(aws ssm get-parameter --name /ganokbot/WEB_SERVER_PORT --with-decryption --query Parameter.Value --output text)" > .env
            echo "DB_NAME=$(aws ssm get-parameter --name /ganokbot/DB_NAME --with-decryption --query Parameter.Value --output text)" >> .env
            echo "DB_HOST=$(aws ssm get-parameter --name /ganokbot/DB_HOST --with-decryption --query Parameter.Value --output text)" >> .env
            echo "DB_PORT=$(aws ssm get-parameter --name /ganokbot/DB_PORT --with-decryption --query Parameter.Value --output text)" >> .env
            echo "DB_USER=$(aws ssm get-parameter --name /ganokbot/DB_USER --with-decryption --query Parameter.Value --output text)" >> .env
            echo "DB_PASSWORD=$(aws ssm get-parameter --name /ganokbot/DB_PASSWORD --with-decryption --query Parameter.Value --output text)" >> .env
            echo "BOT_USERNAME=$(aws ssm get-parameter --name /ganokbot/BOT_USERNAME --with-decryption --query Parameter.Value --output text)" >> .env
            echo "BOT_TOKEN=$(aws ssm get-parameter --name /ganokbot/BOT_TOKEN --with-decryption --query Parameter.Value --output text)" >> .env
            echo "BOT_CREATOR_ID=$(aws ssm get-parameter --name /ganokbot/BOT_CREATOR_ID --with-decryption --query Parameter.Value --output text)" >> .env

            aws ecr get-login-password --region eu-central-1 \
            | docker login --username AWS --password-stdin 220872168257.dkr.ecr.eu-central-1.amazonaws.com
            docker compose pull ganok-bot
            docker compose up -d --force-recreate ganok-bot